# Generated by Django 5.0.4 on 2024-04-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceConnect', '0003_alter_userindividualimage_numpy_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userindividualimage',
            name='i_image',
            field=models.ImageField(upload_to='individual_face_images/'),
        ),
        migrations.AlterField(
            model_name='usermultipleimage',
            name='m_image',
            field=models.ImageField(upload_to='multiple_face_images/'),
        ),
    ]
