# Generated by Django 5.0.4 on 2024-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceConnect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userindividualimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usermultipleimage',
            name='created_by',
        ),
        migrations.AddField(
            model_name='userindividualimage',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usermultipleimage',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
